### ISSUE TITLE
Got the "Task exception was never retrieved" error

### ISSUE THREAD

**Issue by xxks-kkk** [ityoung/python3-fastunit#1]
Thanks for the tool. I got the following error message even all my tests have been executed successfully.
Do you have any clue why?

Thanks!

```
Task exception was never retrieved
future: <Task finished coro=<TestSuite.startRunCase() done, defined at /usr/lib/python3.6/site-packages/fastunit/suite.py:123> exception=ValueError('Set of coroutines/Futures is empty.',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 138, in startRunCase
    await loop.run_in_executor(None, test, result)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 85, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 114, in run
    loop.run_until_complete(asyncio.wait(asyncMethod))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 304, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
Task exception was never retrieved
future: <Task finished coro=<TestSuite.startRunCase() done, defined at /usr/lib/python3.6/site-packages/fastunit/suite.py:123> exception=ValueError('Set of coroutines/Futures is empty.',)>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 138, in startRunCase
    await loop.run_in_executor(None, test, result)
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 85, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.6/site-packages/fastunit/suite.py", line 114, in run
    loop.run_until_complete(asyncio.wait(asyncMethod))
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.6/asyncio/tasks.py", line 304, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
```

**Comment by ityoung** [comment]
@xxks-kkk Sorry about that error, could you provide details of your testcases about how much TestSuites you executed?

**Comment by xxks-kkk** [comment]
Thanks for the reply :) I run two test cases and inside each test case, lots of `subprocess.call` involved. One `subprocess.call` will have an expected runtime error, which is captured by `assertRaises`. Other than those things, I cannot see any difference than any "hello world" cases.

**Comment by ityoung** [comment]
@xxks-kkk Can you try to install the new branch `fixbug/empty-case` and run your test again?

**Comment by ityoung** [comment]
@xxks-kkk And also, I think may have some error in your code. I guess if you run test with the new branch, there will have no testcase be executed.

**Comment by xxks-kkk** [comment]
Thanks for the quick fix. I'll let you know the result when I back to work. Meanwhile, can you explain why you think there might be errors in my test cases? Thanks!

**Comment by ityoung** [comment]
@xxks-kkk From the Line 103 of `fastunit/suite.py` you can see:
```
    def run(self, result, debug=False):
        topLevel = False
        if getattr(result, '_testRunEntered', False) is False:
            result._testRunEntered = topLevel = True
        asyncMethod = []
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        for index, test in enumerate(self):
            asyncMethod.append(self.startRunCase(index, test, result))
        # if asyncMethod:
        loop.run_until_complete(asyncio.wait(asyncMethod))
        loop.close()
        if topLevel:
            self._tearDownPreviousClass(None, result)
            self._handleModuleTearDown(result)
            result._testRunEntered = False
        return result
```

The `asyncMethod` keeps empty when it discovery no testcases, which cause `loop.run_until_complete(asyncio.wait(asyncMethod))` raise that error.

So, I guess your may write a wrong test entry that loads no testcases, and when I add `if asyncMethod:` to skip running empty cases, the bug won't be trigger, but no test will run.

**Comment by xxks-kkk** [comment]
I'm curious if `asyncMethod` is empty, how do my testcases still get executed? In addition, if I use `unittest` instead `fastunit`, everything works fine.

**Comment by xxks-kkk** [comment]
Hello, I figure out the issue. I cannot run `python3.6 -m unittest` when all my test cases actually use `import fastunit as unittest`. In other words, I have to use `fastunit` to invoke the test as well (`python3.6 -m fastunit`).  Thanks for the help.
